### ISSUE TITLE
Can't change counter color

### ISSUE THREAD

**Issue by gabrielzschmitz** [kencx/keyb#1]
It's needed to add a option to change the counter color...

**Comment by gabrielzschmitz** [comment]
If it was written in C I could make a pull request implementing that feature, but I don't really know Go.

**Comment by kencx** [comment]
You can now set the counter color with `counter_fg` and `counter_bg`. Thanks for the suggestion!

**Comment by gabrielzschmitz** [comment]
No problem :)

**Comment by gabrielzschmitz** [comment]
Should add a placeholder _fg and _bg too.
