### ISSUE TITLE
Pick up config file from $XDG_CONFIG_HOME if set

### ISSUE THREAD

**Issue by dlvhdr** [kencx/keyb#11]
I'm on a Mac, but use the XDG dirs.
A lot of apps use these directories even though its not the default mac location.
My suggestion is to use the XDG_CONFIG_HOME env var if it exists and if not fallback to `~/.config`.
If that also doesn't exist, you can fallback to `Application Support`.
I've seen that I can use the `--config` flag but that means I have to use the app with an alias.

**Comment by kencx** [comment]
I'll implement this over the weekend. 

Just to check, the current behaviour is that it uses `Application Support`? I didn't manage to test on macOS so would like to confirm.

**Comment by dlvhdr** [comment]
Yeah the current behaviour is using: `"/Users/dolevh/Library/Application Support/keyb"`
