### ISSUE TITLE
Pressing esc to quit the app

### ISSUE THREAD

**Issue by dlvhdr** [kencx/keyb#17]
I like having esc quit the app. In some apps you can define that as a custom keybinding like in lazygit:
https://github.com/dlvhdr/dotfiles/blob/ea1b3ca38663d7ad56c0c6ffa1581bd0ed010abb/.config/lazygit/config.yml#L36

Currently only q quits the app.

**Comment by kencx** [comment]
Multiple custom bindings can be set in the `quit` field of your config file like so:

```yml
# ~/.config/keyb/config.yml
keys:
  quit: esc, ctrl+c, q
```

But you would still need to press `esc` twice if in search mode. 

The [README](https://github.com/kencx/keyb#hotkeys) has a full list of customizable bindings. I do agree `esc` should be added as default for quitting though.
