### ISSUE TITLE
Clearing display on clear

### ISSUE THREAD

**Issue by Jack-Chronicle** [kencx/keyb#26]
Is it possible to clear the command display after closing it? Whenever I leave it, it just remains above my prompt which is not the best.

If it's possible to implement some way of either having it open its own container, or clearing its output when you exit that would be amazing

**Comment by kencx** [comment]
Fixed in [8374352](https://github.com/kencx/keyb/commit/8374352c80c603fe2e97cd14ad0c8563e5ac706b). Please try it out in v0.7.0!
