### ISSUE TITLE
Spaced Repetition Practice 

### ISSUE THREAD

**Issue by nicoandmee** [kencx/keyb#34]
This is a super useful project. It could be made even better by offering a means to drill/practice keyboard shortcuts, using spaced repetition. This is what [Keycombiner](https://github.com/tkainrad/keycombiner) does, but it hasn't been updated in a long time.

**Comment by kencx** [comment]
Hi, thanks for the suggestion! Unfortunately, I'm not looking to implement this feature, as it is out of scope of this project.
