### ISSUE TITLE
Error when using examples/zsh.yml

### ISSUE THREAD

**Issue by TobberH** [kencx/keyb#8]
keyb: main.go:69: failed to unmarshal keyb file: yaml: line 75: found unknown escape character

**Comment by TobberH** [comment]
go version go1.18.4 linux/amd64

keyb: v0.2.0-2-g25b3eda

**Comment by kencx** [comment]
Thanks for catching this, I didn't check all the examples.

**Comment by kencx** [comment]
Fixed in https://github.com/kencx/keyb/commit/8c9082665cebefdf20cac09aff4e470eb533c9a8
